---

- stat: path="{{ lookup('env','PWD') }}/docker-compose-build.yml"
  register: docker_compose_build

- name: "Build application with Docker Compose, if docker-compose-build.yml exists"
  shell: "docker-compose -f docker-compose-build.yml up"
  when: docker_compose_build.stat.exists
