---

- name: "Log into private registry"
  docker_login:
    registry: "{{ wimpy_docker_registry | default(omit) }}"
    email: "{{ wimpy_docker_registry_email | default(none) }}"
    username: "{{ wimpy_docker_registry_username }}"
    password: "{{ wimpy_docker_registry_password }}"
    reauthorize: yes
  when:
    - not wimpy_docker_skip_login

- name: "Build docker image"
  docker_image:
    path: "{{ lookup('env','PWD') }}"
    name: "{{ wimpy_docker_image_name }}:{{ wimpy_release_version | string }}"
    buildargs: "{{ wimpy_docker_build_args }}"

- name: "Tag docker image with latest"
  docker_image:
    path: "{{ lookup('env','PWD') }}"
    name: "{{ wimpy_docker_image_name }}:latest"
    buildargs: "{{ wimpy_docker_build_args }}"

- name: "Push images to registry"
  docker_image:
    name: "{{ wimpy_docker_image_name }}"
    push: yes
