---

- name: "Log into private registry"
  docker_login:
    registry: "{{ wimpy_docker_registry | default(omit) }}"
    email: "{{ wimpy_docker_registry_email | default(none) }}"
    username: "{{ wimpy_docker_registry_username }}"
    password: "{{ wimpy_docker_registry_password }}"
    reauthorize: yes
  when:
    - not wimpy_docker_skip_login

- name: "Build and push docker image"
  docker_image:
    path: "{{ lookup('env','PWD') }}"
    name: "{{ wimpy_docker_image_name }}:{{ wimpy_release_version | string }}"
    push: yes
    force: "{{ wimpy_docker_image_force }}"
    buildargs: "{{ wimpy_docker_build_args }}"

- name: "Build and push latest tag"
  docker_image:
    path: "{{ lookup('env','PWD') }}"
    name: "{{ wimpy_docker_image_name }}:latest"
    push: yes
    force: "{{ wimpy_docker_image_force }}"
    buildargs: "{{ wimpy_docker_build_args }}"
  when:
    - wimpy_docker_image_tag_latest

