---

- name: "Checking that required parameters are present"
  fail: msg="{{ item }} is a required variable. Set it in your playbook file or pass it as extra var"
  when: not {{ item }} is defined
  with_items:
    - wimpy_application_name
    - wimpy_release_version
