---

- name: "Checking that required parameters are present"
  fail: msg="{{ item }} is a required variable. Set it in your playbook file or pass it as extra var"
  when: not {{ item }} is defined
  with_items:
    - wimpy_project_name
    - wimpy_release_version

- name: "Extract AWS region and account id from registry"
  set_fact:
    wimpy_aws_account_id: "{{ wimpy_docker_registry | regex_replace(wimpy_ecr_pattern, '\\1' ) }}"
    wimpy_aws_region: "{{ wimpy_docker_registry | regex_replace(wimpy_ecr_pattern, '\\2' ) }}"
  when:
    - wimpy_docker_registry is defined
    - wimpy_docker_registry | match(wimpy_ecr_pattern)
